services :
  db:
    image: postgres:16-alpine
    container_name: postgres_tempete_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tempete
      POSTGRES_PASSWORD: RockMetal
      POSTGRES_DB: tempete_db
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: